# Generated by Django 4.2.1 on 2023-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_vote_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
